[target.x86_64-unknown-linux-gnu]
pre-build = [
    "set -e",
    "apt-get update",
    "apt-get install -y --no-install-recommends build-essential protobuf-compiler pkg-config libssl-dev nodejs npm gcc-aarch64-linux-gnu g++-aarch64-linux-gnu",
    "rm -rf /var/lib/apt/lists/*"
]

[target.aarch64-unknown-linux-gnu]
pre-build = [
    "set -e",
    "apt-get update",
    "apt-get install -y --no-install-recommends build-essential protobuf-compiler pkg-config libssl-dev nodejs npm gcc-aarch64-linux-gnu g++-aarch64-linux-gnu",
    "rm -rf /var/lib/apt/lists/*"
]

[target.x86_64-unknown-freebsd]
pre-build = [
    "pkg update",
    "pkg install -y git curl node20 www/npm protobuf ca_root_nss bash gmake pkgconf openssl",
    "export SSL_CERT_FILE=/etc/ssl/cert.pem"
]
